Intoduction to redux
ifzyy/bookstore pull request #2
Opened 2022-08-18 16:13 UTC by ifzyy

### In this milestone

- Write actions and reducer for adding and removing books using the ducks pattern
- Added redux to my project

2022-08-18 17:16 UTC, mukhammadrizooff requested changes
Hi @ifzyy, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 17:16 UTC, mukhammadrizooff commented on src/components/books.js
>      </div>
- [ ] [REQUIRED] Good job so far! You forgot to create `Add` configuration as a physical button. Please fix it!

![image](https://user-images.githubusercontent.com/63915024/185455164-0b97d82b-08e2-440e-9548-40904ec2e786.png)

2022-08-18 17:16 UTC, mukhammadrizooff commented on src/redux/Book/Book.js
> +      return state.filter((book) => book.id !== action.id);
- [ ] [REQUIRED] Your `Delete` button is not working, please fix it and test it!

2022-08-18 19:17 UTC, ifzyy commented
![Screenshot 2022-08-18 201620](https://user-images.githubusercontent.com/92556803/185476201-faf61c46-3bfd-4dad-97a4-921f6f6feec7.png)
The project does not require  delete button code implemented @mukhammadrizooff

2022-08-18 22:06 UTC, mwanawabangona commented on src/redux/Book/Book.js
> +      return state.filter((book) => book.id !== action.id);
- [ ] `required`
- [ ] as mention by the previous reviewer please fix the `Delete Button` as the requirement

2022-08-18 22:11 UTC, mwanawabangona requested changes
Hi, @ifzyy ,

Great work on making the changes requested by a previous reviewer 👏
![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 06:08 UTC, Lameck1 reviewed
Hello @ifzyy 👋,

_This is an additional review due to the second opinion request._

Your implementation of the tasks for this milestone meets expectations. At this point, you are only expected to implement the redux logic. Therefore, you are right.

@mukhammadrizooff & @mwanawabangona, No changes in React components are required in this step. Please take note of this going forward.

As this was the only reason your project was not approved it will be approved as soon as possible.
Just hold on and don't ask for another review, you'll be able to submit this task on your dashboard ASAP.

Keep rocking 🚀

2022-08-19 07:22 UTC, merged